### ISSUE TITLE
请问压缩代码是否只能自己写 gulp 脚本？

### ISSUE THREAD

**Issue by masquevil** [babyzone2004/cocos-fly#1]
您好，最近在学 cocos creator，看到了你的文章，感觉获益匪浅：https://segmentfault.com/a/1190000012424893

目前还有两个主要困扰我的问题，想请教一下：
1. build-template 模板，有模板变量等相关的内置支持吗？现在看起来似乎是一个写死的 html 文件，引用的也只能是 main.js 这样？
2. 现在前端都有比较完善的构建方案，webpack、代码压缩、混淆、版本号等等，用 cocos creator 是只能自己在他生成好的 build 文件基础上，自己用 gulp 之类的工具进行压缩等处理吗

**Comment by babyzone2004** [comment]
1. 有变量支持，但之前cocos文档没有介绍。
2. 用什么工具压缩都可以，只是gulp在这种场景下更合适。另外cocos本身也是用gulp构建。
